export enum AuthErrors {
  LOGIN_USER_NOT_VERIFIED = 'LOGIN_USER_NOT_VERIFIED',
  LOGIN_BAD_CREDENTIALS = 'LOGIN_BAD_CREDENTIALS',
  REGISTER_USER_ALREADY_EXISTS = 'REGISTER_USER_ALREADY_EXISTS',
  REGISTER_INVALID_PASSWORD = 'REGISTER_INVALID_PASSWORD',
}
