name: Frontend_CI

on:
  pull_request:
    branches: ['develop']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint and Format
        run: |
          npm run lint
          npm run lint:fix
          npm run format

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test
        env:
          CI: true
